### ISSUE TITLE
Unexpected results from litstudy.plot_author_histogram()

### ISSUE THREAD

**Issue by larsgrobe** [NLeSC/litstudy#72]
Dear all,

I am observing some unexpected behavior in `litstudy.plot_author_histogram()` in the current master branch. I tried loading bibtex files from Web of Sciences and Scopus, as well as a Scopus csv. In all cases, I get not only a histogram showing the publication counts per author, but I get two histograms (here one blue, one orange), that I can stack. Apparently I have two categories here, but I cannot make sense of this and did not find anything mentioned in the documentation.

Best, Lars.

**Comment by stijnh** [comment]
Thanks for using litstudy and thanks for reporting this issue!

If you do not provide the `groups=` keywords, then it should only draw a single histogram in one color. Make sure to clear the matplotlib canvas between different calls to `plot_...` since otherwise the graphs will be drawn onto the same figure.

Do you have an image of the problem and maybe a relevant code snippet?

**Comment by larsgrobe** [comment]
Thank you - indeed adding a simple `plt.clf()` after calling `plt.savefig()` or `plt.show()` solved this.
